name: ci
on: [push, pull_request]

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup rust
        run: rustup toolchain install stable --profile minimal

      - name: Install nextest to run tests
        uses: taiki-e/install-action@nextest

      - name: Run tests
        run: cargo nextest run --no-fail-fast

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Check clippy
        run: cargo clippy

  test-miri:
    name: Run tests with miri
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout

      - name: Setup rust
        run: rustup toolchain install nightly --profile minimal

      - name: Add miri components
        run: rustup +nightly component add miri rust-src

      - name: Install nextest to run tests
        uses: taiki-e/install-action@nextest

      - name: Run tests
        run: cargo +nightly miri nextest run --no-fail-fast

  msrv:
    name: MSRV check (1.85)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup MSRV rust
        run: rustup toolchain install 1.85 --profile minimal

      - name: Install nextest to run tests
        uses: taiki-e/install-action@nextest

      - name: Check build with MSRV
        run: cargo +1.85 check

      - name: Check tests compile with MSRV
        run: cargo +1.85 nextest run --no-fail-fast
