name: ci
on: [push, pull_request]

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup rust
        run: rustup toolchain install stable --profile minimal

      - name: Install nextest to run tests
        uses: taiki-e/install-action@nextest

      - name: Run tests
        run: cargo nextest run --all-features

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Check clippy
        run: cargo clippy --all-targets --all-features

  msrv:
    name: MSRV check (1.85)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup MSRV rust
        run: rustup toolchain install 1.85 --profile minimal

      - name: Check build with MSRV
        run: cargo +1.85 check --all-targets --all-features

      - name: Check tests compile with MSRV
        run: cargo +1.85 test --all-features --no-run
